$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1435170890554.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStXPosition",
"AxStXPositionOriginal",
"AxStXLimit",
"AxStColumnWidth",
"AxStPickedValue",
"AxStNoItems",
"AxStNoVisibleItems",
"AxStOperation",
"Menu_Variable",
"Menuvariable"],
  "page":{
    "packageId":"ea1c83e1d1494cc9a9a93a5379c84223",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ce932acff7304c5fb53e2bd79dc5fe22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":485,
              "height":780}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d68e4b30482e43c384f74414e9d473f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":485,
                  "height":780}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"7b478534ac7941e29f195c3bc6c507b4",
          "label":"Set Frame Target",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":62},
            "size":{
              "width":360,
              "height":638}},
          "adaptiveStyles":{
},
          "target":{
            "targetType":"page",
            "includeVariables":true}},
{
          "id":"eee99cc653b44cfda9b0f2df294a0033",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":653},
            "size":{
              "width":360,
              "height":50}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9c1ac757ebce4cc798d5607ff82a80d8",
              "label":"White Icons",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f987c640ee46495ab1d5267e2787580d",
                  "label":"BG",
                  "parentDynamicPanel":"eee99cc653b44cfda9b0f2df294a0033",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "location":{
                      "x":-2,
                      "y":-1},
                    "size":{
                      "width":368,
                      "height":53},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f057b820a2164aaab1ac3b68934e2d0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eee99cc653b44cfda9b0f2df294a0033",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "location":{
                          "x":-2,
                          "y":-1},
                        "size":{
                          "width":368,
                          "height":53},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/bg_u4.png"}},
{
                  "id":"55f52e32c1d848e092530d30705ffcee",
                  "label":"Back",
                  "parentDynamicPanel":"eee99cc653b44cfda9b0f2df294a0033",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":69,
                      "y":12},
                    "size":{
                      "width":22,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c16e785c5afb439b8322f6072aca2342",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eee99cc653b44cfda9b0f2df294a0033",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":69,
                          "y":12},
                        "size":{
                          "width":22,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/back_u6.png"}},
{
                  "id":"7e1eadef5452498d8fd8bdb883295f34",
                  "label":"Home",
                  "parentDynamicPanel":"eee99cc653b44cfda9b0f2df294a0033",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":12},
                    "size":{
                      "width":24,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"caef87c8afbe46cfb0f50a9e1cc9e8bf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eee99cc653b44cfda9b0f2df294a0033",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":168,
                          "y":12},
                        "size":{
                          "width":24,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/home_u8.png"}},
{
                  "id":"c5d14943bef742c68bfac62bf1dc745a",
                  "label":"Recent",
                  "parentDynamicPanel":"eee99cc653b44cfda9b0f2df294a0033",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":269,
                      "y":13},
                    "size":{
                      "width":22,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3d6f3bb81d24d8ebaf87b12c2571ed5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eee99cc653b44cfda9b0f2df294a0033",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":269,
                          "y":13},
                        "size":{
                          "width":22,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/recent_u10.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
          "label":"Status Bar",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":61},
            "size":{
              "width":364,
              "height":26}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"97e4915264134a4ab81cde715d6dcff1",
              "label":"Status Bar",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5e792bcd9dc8442c868601796b9db572",
                  "label":"Status BG Color",
                  "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF1F272A},
                    "location":{
                      "x":-1,
                      "y":-1},
                    "size":{
                      "width":364,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"036eb8cb187c400ca3d79a0477588644",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF1F272A},
                        "location":{
                          "x":-1,
                          "y":-1},
                        "size":{
                          "width":364,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/status_bg_color_u13.png"}},
{
                  "id":"f1746935167740f6bda93d0dfeee3292",
                  "label":"Time",
                  "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'Roboto Regular', 'Roboto'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":686,
                      "y":5},
                    "size":{
                      "width":28,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7430cb7f34d46d9b0ff89f249b58037",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Roboto Regular', 'Roboto'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":686,
                          "y":5},
                        "size":{
                          "width":28,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0001d7227fd24772a097e3217f17a77a",
                  "label":"Status Battery Icon",
                  "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":308,
                      "y":4},
                    "size":{
                      "width":15,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6574423985c0423da5787d57de5b76ae",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":308,
                          "y":4},
                        "size":{
                          "width":15,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/status_battery_icon_u17.png"}},
{
                  "id":"a5024079d3044906bb497b3b11bd5be0",
                  "label":"Status Wifi Icon",
                  "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":264,
                      "y":2},
                    "size":{
                      "width":21,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93763e6cc4d342a4893473b60e36abf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":264,
                          "y":2},
                        "size":{
                          "width":21,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/status_wifi_icon_u19.png"}},
{
                  "id":"dfa6b72af0324b678701c01d25713edb",
                  "label":"Status Network Icon",
                  "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":286,
                      "y":4},
                    "size":{
                      "width":18,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aec53d650ec44438aca4a54f9c7c15dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":286,
                          "y":4},
                        "size":{
                          "width":18,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/status_network_icon_u21.png"}},
{
                  "id":"42963b11454448e38951d3423e44648c",
                  "label":"Time",
                  "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'Roboto Regular', 'Roboto'",
                    "fontSize":"14px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":327,
                      "y":5},
                    "size":{
                      "width":28,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa58f1a7ea764dc6a8579be76c5f4308",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f5b14216b5c347ccbfa99e6c5bd5e4f3",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Roboto Regular', 'Roboto'",
                        "fontSize":"14px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":327,
                          "y":5},
                        "size":{
                          "width":28,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"14c87b0c1e5d4001b5120720616681ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":85},
            "size":{
              "width":360,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f437cdf54364d018fb71e298987065a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":85},
                "size":{
                  "width":360,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u25.png"}},
{
          "id":"9e293e0b53ac4bbab981dd2365d9cded",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6fad1dc0258e4bb2ae7957b942e6ba8a"},
{
          "id":"78e20f127f604c85a01ff21fc6368a76",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":130},
            "size":{
              "width":359,
              "height":477}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4431df8aec6e4cf28a75f8526f72d079",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cdabd9d2d93e4fce9524c9027bdc035f",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":359,
                      "height":2810}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f81bdab39a742a186cb99dacf3cd849",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":359,
                          "height":2810}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u64.png"}},
{
                  "id":"3c718caeec8644bda5f00064e1b1fa57",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":23},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d2dc6d485244481942c0fc65f43489d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":23},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"6b7f6bd47f944e90bddf8786cb520e82",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":278},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ff2922f4c924c81b5fd6e91ac352c43",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":278},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"ace786e687934b3e9f1ba82911e6e1cc",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":534},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e2d1d4aa1f1a447ea3671869d282171a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":534},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"15aa166ef2c442639950961b5bbe8a01",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":789},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e8c33b04966340d7b0bdf9792e62a8e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":789},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"41f8e9808bf9421396374a3a0b4ed7a1",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":1044},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7aabb2e32b3940c6806a2eeff0275753",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":1044},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"aa6db0b327f941c2a17e64fb44724c58",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":1300},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3dd59b8a906e4944915b871c2991d319",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":1300},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"52e6763bcc3a4ae0abe2ccae3bccd73f",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":1555},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c9c99dc49bb74d928ee0b40262185f2e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":1555},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"6f8e2ac45b0a4b2abd8588145075246c",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":1810},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a569ec2aff924829b043293d2f02479f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":1810},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"56af7c660f244c78a05d4b481f5d5d42",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":2065},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46db2dbf1f1745cba484398f0a475ed3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":2065},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"b1b3e06640444ef8a799495ff56e6ea5",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":2321},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf33605f81ef4f4a8c3c028900cc5772",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":2321},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}},
{
                  "id":"638c6876f0b04059812b3d1093ddf06d",
                  "label":"",
                  "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":2576},
                    "size":{
                      "width":333,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99c1224397d94dcca538af71107f993b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"78e20f127f604c85a01ff21fc6368a76",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":2576},
                        "size":{
                          "width":333,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u66.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d239d68cffae4761b9af277eeb9138e6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"3210493e7900491d8ead93e4be954f9c"}]}},
  "masters":{
    "6fad1dc0258e4bb2ae7957b942e6ba8a":{
      "packageId":"6fad1dc0258e4bb2ae7957b942e6ba8a",
      "type":"Axure:Master",
      "name":"Mobile Master",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"304098334a3a436eba10bdfe9ddbdf3c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":485,
                "height":780}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d2ab26177fe94ea7a08e14bd1d7dbf1f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":485,
                    "height":780}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u0.png"}},
{
            "id":"7468122d704c4b28841f9104d62ed0c6",
            "label":"Set Frame Target",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":62,
                "y":64},
              "size":{
                "width":360,
                "height":638}},
            "adaptiveStyles":{
},
            "target":{
              "targetType":"page",
              "includeVariables":true}},
{
            "id":"b4699e436f284745b8eff14d44c41e0e",
            "label":"Status Bar",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":62,
                "y":63},
              "size":{
                "width":364,
                "height":26}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"714a12bce2414084be2adae65cf38c45",
                "label":"Status Bar",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"ed3d4ae09a9a4c2faf68d7e710667f75",
                    "label":"Status BG Color",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF1F272A},
                      "location":{
                        "x":-1,
                        "y":-1},
                      "size":{
                        "width":364,
                        "height":30},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"454e729c1c3e46a5a1796054fef6b520",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF1F272A},
                          "location":{
                            "x":-1,
                            "y":-1},
                          "size":{
                            "width":364,
                            "height":30},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/status_bg_color_u13.png"}},
{
                    "id":"2786e32a569f4cd7b2f615ada35b8147",
                    "label":"Time",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Roboto Regular', 'Roboto'",
                      "fontSize":"14px",
                      "fontWeight":"400",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "location":{
                        "x":686,
                        "y":5},
                      "size":{
                        "width":28,
                        "height":17}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8765d64bf38a4b499bf0317d174aa62b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Roboto Regular', 'Roboto'",
                          "fontSize":"14px",
                          "fontWeight":"400",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "location":{
                            "x":686,
                            "y":5},
                          "size":{
                            "width":28,
                            "height":17}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"088294d0af4044b8b630daffefe0bae3",
                    "label":"Status Battery Icon",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":308,
                        "y":4},
                      "size":{
                        "width":15,
                        "height":17}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5f2c1186e4c3401cb42b8c9254353732",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":308,
                            "y":4},
                          "size":{
                            "width":15,
                            "height":17}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/status_battery_icon_u17.png"}},
{
                    "id":"d9f44c8297c541d7a6830cf4c4465c47",
                    "label":"Status Wifi Icon",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":264,
                        "y":2},
                      "size":{
                        "width":21,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8b189d5e9a09439a8c02f8ba2c984e9a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":264,
                            "y":2},
                          "size":{
                            "width":21,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/status_wifi_icon_u19.png"}},
{
                    "id":"1928623f2e2d4e3f9db1e9942b1e9697",
                    "label":"Status Network Icon",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":286,
                        "y":4},
                      "size":{
                        "width":18,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1aefd94ec79e4958b91b9a653c2cfdce",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":286,
                            "y":4},
                          "size":{
                            "width":18,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/status_network_icon_u21.png"}},
{
                    "id":"e07464a117394704ae661dbe7ae08027",
                    "label":"Time",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Roboto Regular', 'Roboto'",
                      "fontSize":"14px",
                      "fontWeight":"400",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "location":{
                        "x":327,
                        "y":5},
                      "size":{
                        "width":28,
                        "height":17}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3cbca462278a452a8605001a37f4a2f2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Roboto Regular', 'Roboto'",
                          "fontSize":"14px",
                          "fontWeight":"400",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "location":{
                            "x":327,
                            "y":5},
                          "size":{
                            "width":28,
                            "height":17}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"1fc549ae4cee485eaf32e9aa544d9b2c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":62,
                "y":107},
              "size":{
                "width":360,
                "height":568}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a7ce32f7f10455697cf4d25000e80d5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":62,
                    "y":107},
                  "size":{
                    "width":360,
                    "height":568}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u25.png"}},
{
            "id":"06e98ae149ea42d293332f8d2d7f03bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":62,
                "y":607},
              "size":{
                "width":360,
                "height":47}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93b616f0476843e280ecc97237d38803",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":62,
                    "y":607},
                  "size":{
                    "width":360,
                    "height":47}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u46.png"}},
{
            "id":"69d2ad3de5324d6ea231a8c6da194c42",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":143,
                "y":614},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0f01366f0c984a7693f422b3718ba8bb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":143,
                    "y":614},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u48.png"}},
{
            "id":"71e65a8653c540008a8411748dc29f28",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":307,
                "y":614},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed498836e0be4dffaa8865b111ef5fac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":307,
                    "y":614},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u50.png"}},
{
            "id":"fced2d6de5b348ac92b496b2409acf9d",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":221,
                "y":614},
              "size":{
                "width":40,
                "height":29}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open CV in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"cv.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5035dda8863442b48f723d72b55bc897",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":62,
                "y":654},
              "size":{
                "width":360,
                "height":50}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"1c67e7df8aff4f2c873ea317975ee380",
                "label":"White Icons",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"f9c9b5abb089402aae3c6245a47bbb73",
                    "label":"BG",
                    "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":-2,
                        "y":-1},
                      "size":{
                        "width":368,
                        "height":53},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"07ad2066a5a140e09d2a5789515c9cd2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":-2,
                            "y":-1},
                          "size":{
                            "width":368,
                            "height":53},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/bg_u4.png"}},
{
                    "id":"100a622006304863b66ea184ac4326c1",
                    "label":"Back",
                    "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":69,
                        "y":12},
                      "size":{
                        "width":22,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"10335ed04b6641bab6dd417f730971ea",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":69,
                            "y":12},
                          "size":{
                            "width":22,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/back_u6.png"}},
{
                    "id":"152775203b2f486991bda12548664a94",
                    "label":"Home",
                    "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":168,
                        "y":12},
                      "size":{
                        "width":24,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"69dd513202904c33a2dab3ff2f4cf05d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":168,
                            "y":12},
                          "size":{
                            "width":24,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/home_u8.png"}},
{
                    "id":"690906ffcc0342d0b5b433c1f959fc5d",
                    "label":"Recent",
                    "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":269,
                        "y":13},
                      "size":{
                        "width":22,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3574f624fcd24af484fecb5f5f64994e",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":269,
                            "y":13},
                          "size":{
                            "width":22,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/recent_u10.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"ba6bdb6b81a24125b6e1eb05b7beffb3",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":120,
                "y":653},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Mobile back button",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Back in Current Window",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "3210493e7900491d8ead93e4be954f9c":{
      "packageId":"3210493e7900491d8ead93e4be954f9c",
      "type":"Axure:Master",
      "name":"App Header Master",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"04d8d786be5948b2a1280425060b7c44",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":62,
                "y":85},
              "size":{
                "width":360,
                "height":47}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f42407941a7c4be9a80e1c1241fc1470",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":62,
                    "y":85},
                  "size":{
                    "width":360,
                    "height":47}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u46.png"}},
{
            "id":"a6b2e4aa0f0b4355a4b7742449541154",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":114,
                "y":88},
              "size":{
                "width":72,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed64001a4f7b4eafbf19fd06486971f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":114,
                    "y":88},
                  "size":{
                    "width":72,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u91.png"}},
{
            "id":"9d2df81f1f4b4e0790c44855f0f444f9",
            "label":"Menu",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":69,
                "y":87},
              "size":{
                "width":38,
                "height":38}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4609c8701294459b868e5eda24675efd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":69,
                    "y":87},
                  "size":{
                    "width":38,
                    "height":38}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"ShowMenu<br> (If value of Menuvariable equals &quot;False&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Menuvariable"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"False",
                        "stos":[]}},
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show Menu DP slide right 500 ms",
                        "objectsToFades":[{
                            "objectPath":["d391f367d9984842b0b35554f6f00dc5"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"slideRight",
                                "duration":500,
                                "showType":"none"}}}]},
{
                        "action":"setFunction",
                        "description":"Set value of Menuvariable equal to &quot;True&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"Menuvariable"},
{
                                  "exprType":"stringLiteral",
                                  "value":"True",
                                  "stos":[]}]}]}}]},
{
                    "description":"HideMenu<br> (Else If True)",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide Menu DP slide left 500 ms",
                        "objectsToFades":[{
                            "objectPath":["d391f367d9984842b0b35554f6f00dc5"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "easing":"slideLeft",
                                "duration":500,
                                "showType":"none"}}}]},
{
                        "action":"setFunction",
                        "description":"Set value of Menuvariable equal to &quot;False&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"Menuvariable"},
{
                                  "exprType":"stringLiteral",
                                  "value":"False",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/menu_u93.png"}},
{
            "id":"d391f367d9984842b0b35554f6f00dc5",
            "label":"Menu DP",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":62,
                "y":132},
              "size":{
                "width":158,
                "height":475},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"fc84ffa8690f4fe099b26af0c7b120f4",
                "label":"State1. Menu",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"4928784be90b43ec9fc731f44933e869",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF999999},
                      "location":{
                        "x":0,
                        "y":-6},
                      "size":{
                        "width":160,
                        "height":486}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ca8b8bf7135d479ebe208ebc3b3c7011",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF999999},
                          "location":{
                            "x":0,
                            "y":-6},
                          "size":{
                            "width":160,
                            "height":486}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u96.png"}},
{
                    "id":"cbbd110ef5e0402cad1d6672289a6e05",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontWeight":"700",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":5,
                        "y":60},
                      "size":{
                        "width":150,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open My Profile in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"my_profile.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"8701e14eaa6946c280e59fd424ea4bdd",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontWeight":"700",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":5,
                        "y":135},
                      "size":{
                        "width":150,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Ref and Testimonial in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"ref_and_testimonial.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"a9ca792fe30e4ab0982edbe4eaeb4340",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontWeight":"700",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":5,
                        "y":98},
                      "size":{
                        "width":150,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Expertise in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"expertise.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"8a47196aad3f420088144573216e183f",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontWeight":"700",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":5,
                        "y":23},
                      "size":{
                        "width":150,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "ce932acff7304c5fb53e2bd79dc5fe22":{
      "scriptId":"u0"},
    "d68e4b30482e43c384f74414e9d473f5":{
      "scriptId":"u1"},
    "7b478534ac7941e29f195c3bc6c507b4":{
      "scriptId":"u2"},
    "eee99cc653b44cfda9b0f2df294a0033":{
      "scriptId":"u3"},
    "f987c640ee46495ab1d5267e2787580d":{
      "scriptId":"u4"},
    "f057b820a2164aaab1ac3b68934e2d0a":{
      "scriptId":"u5"},
    "55f52e32c1d848e092530d30705ffcee":{
      "scriptId":"u6"},
    "c16e785c5afb439b8322f6072aca2342":{
      "scriptId":"u7"},
    "7e1eadef5452498d8fd8bdb883295f34":{
      "scriptId":"u8"},
    "caef87c8afbe46cfb0f50a9e1cc9e8bf":{
      "scriptId":"u9"},
    "c5d14943bef742c68bfac62bf1dc745a":{
      "scriptId":"u10"},
    "a3d6f3bb81d24d8ebaf87b12c2571ed5":{
      "scriptId":"u11"},
    "f5b14216b5c347ccbfa99e6c5bd5e4f3":{
      "scriptId":"u12"},
    "5e792bcd9dc8442c868601796b9db572":{
      "scriptId":"u13"},
    "036eb8cb187c400ca3d79a0477588644":{
      "scriptId":"u14"},
    "f1746935167740f6bda93d0dfeee3292":{
      "scriptId":"u15"},
    "a7430cb7f34d46d9b0ff89f249b58037":{
      "scriptId":"u16"},
    "0001d7227fd24772a097e3217f17a77a":{
      "scriptId":"u17"},
    "6574423985c0423da5787d57de5b76ae":{
      "scriptId":"u18"},
    "a5024079d3044906bb497b3b11bd5be0":{
      "scriptId":"u19"},
    "93763e6cc4d342a4893473b60e36abf4":{
      "scriptId":"u20"},
    "dfa6b72af0324b678701c01d25713edb":{
      "scriptId":"u21"},
    "aec53d650ec44438aca4a54f9c7c15dd":{
      "scriptId":"u22"},
    "42963b11454448e38951d3423e44648c":{
      "scriptId":"u23"},
    "fa58f1a7ea764dc6a8579be76c5f4308":{
      "scriptId":"u24"},
    "14c87b0c1e5d4001b5120720616681ab":{
      "scriptId":"u25"},
    "1f437cdf54364d018fb71e298987065a":{
      "scriptId":"u26"},
    "9e293e0b53ac4bbab981dd2365d9cded":{
      "scriptId":"u27",
      "304098334a3a436eba10bdfe9ddbdf3c":{
        "scriptId":"u28"},
      "d2ab26177fe94ea7a08e14bd1d7dbf1f":{
        "scriptId":"u29"},
      "7468122d704c4b28841f9104d62ed0c6":{
        "scriptId":"u30"},
      "b4699e436f284745b8eff14d44c41e0e":{
        "scriptId":"u31"},
      "ed3d4ae09a9a4c2faf68d7e710667f75":{
        "scriptId":"u32"},
      "454e729c1c3e46a5a1796054fef6b520":{
        "scriptId":"u33"},
      "2786e32a569f4cd7b2f615ada35b8147":{
        "scriptId":"u34"},
      "8765d64bf38a4b499bf0317d174aa62b":{
        "scriptId":"u35"},
      "088294d0af4044b8b630daffefe0bae3":{
        "scriptId":"u36"},
      "5f2c1186e4c3401cb42b8c9254353732":{
        "scriptId":"u37"},
      "d9f44c8297c541d7a6830cf4c4465c47":{
        "scriptId":"u38"},
      "8b189d5e9a09439a8c02f8ba2c984e9a":{
        "scriptId":"u39"},
      "1928623f2e2d4e3f9db1e9942b1e9697":{
        "scriptId":"u40"},
      "1aefd94ec79e4958b91b9a653c2cfdce":{
        "scriptId":"u41"},
      "e07464a117394704ae661dbe7ae08027":{
        "scriptId":"u42"},
      "3cbca462278a452a8605001a37f4a2f2":{
        "scriptId":"u43"},
      "1fc549ae4cee485eaf32e9aa544d9b2c":{
        "scriptId":"u44"},
      "0a7ce32f7f10455697cf4d25000e80d5":{
        "scriptId":"u45"},
      "06e98ae149ea42d293332f8d2d7f03bc":{
        "scriptId":"u46"},
      "93b616f0476843e280ecc97237d38803":{
        "scriptId":"u47"},
      "69d2ad3de5324d6ea231a8c6da194c42":{
        "scriptId":"u48"},
      "0f01366f0c984a7693f422b3718ba8bb":{
        "scriptId":"u49"},
      "71e65a8653c540008a8411748dc29f28":{
        "scriptId":"u50"},
      "ed498836e0be4dffaa8865b111ef5fac":{
        "scriptId":"u51"},
      "fced2d6de5b348ac92b496b2409acf9d":{
        "scriptId":"u52"},
      "5035dda8863442b48f723d72b55bc897":{
        "scriptId":"u53"},
      "f9c9b5abb089402aae3c6245a47bbb73":{
        "scriptId":"u54"},
      "07ad2066a5a140e09d2a5789515c9cd2":{
        "scriptId":"u55"},
      "100a622006304863b66ea184ac4326c1":{
        "scriptId":"u56"},
      "10335ed04b6641bab6dd417f730971ea":{
        "scriptId":"u57"},
      "152775203b2f486991bda12548664a94":{
        "scriptId":"u58"},
      "69dd513202904c33a2dab3ff2f4cf05d":{
        "scriptId":"u59"},
      "690906ffcc0342d0b5b433c1f959fc5d":{
        "scriptId":"u60"},
      "3574f624fcd24af484fecb5f5f64994e":{
        "scriptId":"u61"},
      "ba6bdb6b81a24125b6e1eb05b7beffb3":{
        "scriptId":"u62"}},
    "78e20f127f604c85a01ff21fc6368a76":{
      "scriptId":"u63"},
    "cdabd9d2d93e4fce9524c9027bdc035f":{
      "scriptId":"u64"},
    "3f81bdab39a742a186cb99dacf3cd849":{
      "scriptId":"u65"},
    "3c718caeec8644bda5f00064e1b1fa57":{
      "scriptId":"u66"},
    "7d2dc6d485244481942c0fc65f43489d":{
      "scriptId":"u67"},
    "6b7f6bd47f944e90bddf8786cb520e82":{
      "scriptId":"u68"},
    "1ff2922f4c924c81b5fd6e91ac352c43":{
      "scriptId":"u69"},
    "ace786e687934b3e9f1ba82911e6e1cc":{
      "scriptId":"u70"},
    "e2d1d4aa1f1a447ea3671869d282171a":{
      "scriptId":"u71"},
    "15aa166ef2c442639950961b5bbe8a01":{
      "scriptId":"u72"},
    "e8c33b04966340d7b0bdf9792e62a8e5":{
      "scriptId":"u73"},
    "41f8e9808bf9421396374a3a0b4ed7a1":{
      "scriptId":"u74"},
    "7aabb2e32b3940c6806a2eeff0275753":{
      "scriptId":"u75"},
    "aa6db0b327f941c2a17e64fb44724c58":{
      "scriptId":"u76"},
    "3dd59b8a906e4944915b871c2991d319":{
      "scriptId":"u77"},
    "52e6763bcc3a4ae0abe2ccae3bccd73f":{
      "scriptId":"u78"},
    "c9c99dc49bb74d928ee0b40262185f2e":{
      "scriptId":"u79"},
    "6f8e2ac45b0a4b2abd8588145075246c":{
      "scriptId":"u80"},
    "a569ec2aff924829b043293d2f02479f":{
      "scriptId":"u81"},
    "56af7c660f244c78a05d4b481f5d5d42":{
      "scriptId":"u82"},
    "46db2dbf1f1745cba484398f0a475ed3":{
      "scriptId":"u83"},
    "b1b3e06640444ef8a799495ff56e6ea5":{
      "scriptId":"u84"},
    "cf33605f81ef4f4a8c3c028900cc5772":{
      "scriptId":"u85"},
    "638c6876f0b04059812b3d1093ddf06d":{
      "scriptId":"u86"},
    "99c1224397d94dcca538af71107f993b":{
      "scriptId":"u87"},
    "d239d68cffae4761b9af277eeb9138e6":{
      "scriptId":"u88",
      "04d8d786be5948b2a1280425060b7c44":{
        "scriptId":"u89"},
      "f42407941a7c4be9a80e1c1241fc1470":{
        "scriptId":"u90"},
      "a6b2e4aa0f0b4355a4b7742449541154":{
        "scriptId":"u91"},
      "ed64001a4f7b4eafbf19fd06486971f4":{
        "scriptId":"u92"},
      "9d2df81f1f4b4e0790c44855f0f444f9":{
        "scriptId":"u93"},
      "4609c8701294459b868e5eda24675efd":{
        "scriptId":"u94"},
      "d391f367d9984842b0b35554f6f00dc5":{
        "scriptId":"u95"},
      "4928784be90b43ec9fc731f44933e869":{
        "scriptId":"u96"},
      "ca8b8bf7135d479ebe208ebc3b3c7011":{
        "scriptId":"u97"},
      "cbbd110ef5e0402cad1d6672289a6e05":{
        "scriptId":"u98"},
      "8701e14eaa6946c280e59fd424ea4bdd":{
        "scriptId":"u99"},
      "a9ca792fe30e4ab0982edbe4eaeb4340":{
        "scriptId":"u100"},
      "8a47196aad3f420088144573216e183f":{
        "scriptId":"u101"}}}});