$axure.loadCurrentPage({
  "url":"cv.html",
  "generationDate":new Date(1435170890812.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStXPosition",
"AxStXPositionOriginal",
"AxStXLimit",
"AxStColumnWidth",
"AxStPickedValue",
"AxStNoItems",
"AxStNoVisibleItems",
"AxStOperation",
"Menu_Variable",
"Menuvariable"],
  "page":{
    "packageId":"995c93012698465b94be34c1a9667db6",
    "type":"Axure:Page",
    "name":"CV",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0eafc0e48886443d9e542f99ed5e42aa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6fad1dc0258e4bb2ae7957b942e6ba8a"},
{
          "id":"278515e4f5144b858ed66df9685b9651",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":195},
            "size":{
              "width":334,
              "height":412}},
          "adaptiveStyles":{
},
          "scrollbars":"verticalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9806ef8097294a9a82d4a3ddd99c083b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3054193e20524a489bfe464824653dba",
                  "label":"",
                  "parentDynamicPanel":"278515e4f5144b858ed66df9685b9651",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":334,
                      "height":2226}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c4355b83d5e42d2a5c298109617117e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"278515e4f5144b858ed66df9685b9651",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":334,
                          "height":2226}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e0229760a30b4827a1292be5da3c055f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":132.5,
              "y":156},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"91b090229e9b48dc985e3af9a7ca5838",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"3210493e7900491d8ead93e4be954f9c"}]}},
  "masters":{
    "6fad1dc0258e4bb2ae7957b942e6ba8a":{
      "packageId":"6fad1dc0258e4bb2ae7957b942e6ba8a",
      "type":"Axure:Master",
      "name":"Mobile Master",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"304098334a3a436eba10bdfe9ddbdf3c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":485,
                "height":780}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d2ab26177fe94ea7a08e14bd1d7dbf1f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":485,
                    "height":780}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u0.png"}},
{
            "id":"7468122d704c4b28841f9104d62ed0c6",
            "label":"Set Frame Target",
            "type":"inlineFrame",
            "styleType":"inlineFrame",
            "visible":true,
            "style":{
              "location":{
                "x":62,
                "y":64},
              "size":{
                "width":360,
                "height":638}},
            "adaptiveStyles":{
},
            "target":{
              "targetType":"page",
              "includeVariables":true}},
{
            "id":"b4699e436f284745b8eff14d44c41e0e",
            "label":"Status Bar",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":62,
                "y":63},
              "size":{
                "width":364,
                "height":26}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"714a12bce2414084be2adae65cf38c45",
                "label":"Status Bar",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"ed3d4ae09a9a4c2faf68d7e710667f75",
                    "label":"Status BG Color",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF1F272A},
                      "location":{
                        "x":-1,
                        "y":-1},
                      "size":{
                        "width":364,
                        "height":30},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"454e729c1c3e46a5a1796054fef6b520",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF1F272A},
                          "location":{
                            "x":-1,
                            "y":-1},
                          "size":{
                            "width":364,
                            "height":30},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/status_bg_color_u13.png"}},
{
                    "id":"2786e32a569f4cd7b2f615ada35b8147",
                    "label":"Time",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Roboto Regular', 'Roboto'",
                      "fontSize":"14px",
                      "fontWeight":"400",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "location":{
                        "x":686,
                        "y":5},
                      "size":{
                        "width":28,
                        "height":17}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8765d64bf38a4b499bf0317d174aa62b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Roboto Regular', 'Roboto'",
                          "fontSize":"14px",
                          "fontWeight":"400",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "location":{
                            "x":686,
                            "y":5},
                          "size":{
                            "width":28,
                            "height":17}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"088294d0af4044b8b630daffefe0bae3",
                    "label":"Status Battery Icon",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":308,
                        "y":4},
                      "size":{
                        "width":15,
                        "height":17}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5f2c1186e4c3401cb42b8c9254353732",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":308,
                            "y":4},
                          "size":{
                            "width":15,
                            "height":17}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/status_battery_icon_u17.png"}},
{
                    "id":"d9f44c8297c541d7a6830cf4c4465c47",
                    "label":"Status Wifi Icon",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":264,
                        "y":2},
                      "size":{
                        "width":21,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8b189d5e9a09439a8c02f8ba2c984e9a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":264,
                            "y":2},
                          "size":{
                            "width":21,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/status_wifi_icon_u19.png"}},
{
                    "id":"1928623f2e2d4e3f9db1e9942b1e9697",
                    "label":"Status Network Icon",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":286,
                        "y":4},
                      "size":{
                        "width":18,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1aefd94ec79e4958b91b9a653c2cfdce",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":286,
                            "y":4},
                          "size":{
                            "width":18,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/status_network_icon_u21.png"}},
{
                    "id":"e07464a117394704ae661dbe7ae08027",
                    "label":"Time",
                    "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontName":"'Roboto Regular', 'Roboto'",
                      "fontSize":"14px",
                      "fontWeight":"400",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "location":{
                        "x":327,
                        "y":5},
                      "size":{
                        "width":28,
                        "height":17}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3cbca462278a452a8605001a37f4a2f2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b4699e436f284745b8eff14d44c41e0e",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Roboto Regular', 'Roboto'",
                          "fontSize":"14px",
                          "fontWeight":"400",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "location":{
                            "x":327,
                            "y":5},
                          "size":{
                            "width":28,
                            "height":17}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"1fc549ae4cee485eaf32e9aa544d9b2c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":62,
                "y":107},
              "size":{
                "width":360,
                "height":568}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0a7ce32f7f10455697cf4d25000e80d5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":62,
                    "y":107},
                  "size":{
                    "width":360,
                    "height":568}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u25.png"}},
{
            "id":"06e98ae149ea42d293332f8d2d7f03bc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":62,
                "y":607},
              "size":{
                "width":360,
                "height":47}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93b616f0476843e280ecc97237d38803",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":62,
                    "y":607},
                  "size":{
                    "width":360,
                    "height":47}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u46.png"}},
{
            "id":"69d2ad3de5324d6ea231a8c6da194c42",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":143,
                "y":614},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0f01366f0c984a7693f422b3718ba8bb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":143,
                    "y":614},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u48.png"}},
{
            "id":"71e65a8653c540008a8411748dc29f28",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":307,
                "y":614},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed498836e0be4dffaa8865b111ef5fac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":307,
                    "y":614},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u50.png"}},
{
            "id":"fced2d6de5b348ac92b496b2409acf9d",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "horizontalAlignment":"center",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":221,
                "y":614},
              "size":{
                "width":40,
                "height":29}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open CV in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"cv.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5035dda8863442b48f723d72b55bc897",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":62,
                "y":654},
              "size":{
                "width":360,
                "height":50}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"1c67e7df8aff4f2c873ea317975ee380",
                "label":"White Icons",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"f9c9b5abb089402aae3c6245a47bbb73",
                    "label":"BG",
                    "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":-2,
                        "y":-1},
                      "size":{
                        "width":368,
                        "height":53},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"07ad2066a5a140e09d2a5789515c9cd2",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":-2,
                            "y":-1},
                          "size":{
                            "width":368,
                            "height":53},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/bg_u4.png"}},
{
                    "id":"100a622006304863b66ea184ac4326c1",
                    "label":"Back",
                    "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":69,
                        "y":12},
                      "size":{
                        "width":22,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"10335ed04b6641bab6dd417f730971ea",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":69,
                            "y":12},
                          "size":{
                            "width":22,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/back_u6.png"}},
{
                    "id":"152775203b2f486991bda12548664a94",
                    "label":"Home",
                    "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":168,
                        "y":12},
                      "size":{
                        "width":24,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"69dd513202904c33a2dab3ff2f4cf05d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":168,
                            "y":12},
                          "size":{
                            "width":24,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/home_u8.png"}},
{
                    "id":"690906ffcc0342d0b5b433c1f959fc5d",
                    "label":"Recent",
                    "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                    "panelIndex":0,
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":269,
                        "y":13},
                      "size":{
                        "width":22,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3574f624fcd24af484fecb5f5f64994e",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"5035dda8863442b48f723d72b55bc897",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":269,
                            "y":13},
                          "size":{
                            "width":22,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/recent_u10.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"ba6bdb6b81a24125b6e1eb05b7beffb3",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":120,
                "y":653},
              "size":{
                "width":50,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Mobile back button",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Back in Current Window",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "3210493e7900491d8ead93e4be954f9c":{
      "packageId":"3210493e7900491d8ead93e4be954f9c",
      "type":"Axure:Master",
      "name":"App Header Master",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"04d8d786be5948b2a1280425060b7c44",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":62,
                "y":85},
              "size":{
                "width":360,
                "height":47}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f42407941a7c4be9a80e1c1241fc1470",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":62,
                    "y":85},
                  "size":{
                    "width":360,
                    "height":47}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u46.png"}},
{
            "id":"a6b2e4aa0f0b4355a4b7742449541154",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":114,
                "y":88},
              "size":{
                "width":72,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed64001a4f7b4eafbf19fd06486971f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":114,
                    "y":88},
                  "size":{
                    "width":72,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u91.png"}},
{
            "id":"9d2df81f1f4b4e0790c44855f0f444f9",
            "label":"Menu",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":69,
                "y":87},
              "size":{
                "width":38,
                "height":38}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4609c8701294459b868e5eda24675efd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":69,
                    "y":87},
                  "size":{
                    "width":38,
                    "height":38}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"ShowMenu<br> (If value of Menuvariable equals &quot;False&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Menuvariable"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"False",
                        "stos":[]}},
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show Menu DP slide right 500 ms",
                        "objectsToFades":[{
                            "objectPath":["d391f367d9984842b0b35554f6f00dc5"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"slideRight",
                                "duration":500,
                                "showType":"none"}}}]},
{
                        "action":"setFunction",
                        "description":"Set value of Menuvariable equal to &quot;True&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"Menuvariable"},
{
                                  "exprType":"stringLiteral",
                                  "value":"True",
                                  "stos":[]}]}]}}]},
{
                    "description":"HideMenu<br> (Else If True)",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide Menu DP slide left 500 ms",
                        "objectsToFades":[{
                            "objectPath":["d391f367d9984842b0b35554f6f00dc5"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "easing":"slideLeft",
                                "duration":500,
                                "showType":"none"}}}]},
{
                        "action":"setFunction",
                        "description":"Set value of Menuvariable equal to &quot;False&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"Menuvariable"},
{
                                  "exprType":"stringLiteral",
                                  "value":"False",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/menu_u93.png"}},
{
            "id":"d391f367d9984842b0b35554f6f00dc5",
            "label":"Menu DP",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":62,
                "y":132},
              "size":{
                "width":158,
                "height":475},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"fc84ffa8690f4fe099b26af0c7b120f4",
                "label":"State1. Menu",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"4928784be90b43ec9fc731f44933e869",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF999999},
                      "location":{
                        "x":0,
                        "y":-6},
                      "size":{
                        "width":160,
                        "height":486}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ca8b8bf7135d479ebe208ebc3b3c7011",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF999999},
                          "location":{
                            "x":0,
                            "y":-6},
                          "size":{
                            "width":160,
                            "height":486}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u96.png"}},
{
                    "id":"cbbd110ef5e0402cad1d6672289a6e05",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontWeight":"700",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":5,
                        "y":60},
                      "size":{
                        "width":150,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open My Profile in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"my_profile.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"8701e14eaa6946c280e59fd424ea4bdd",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontWeight":"700",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":5,
                        "y":135},
                      "size":{
                        "width":150,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Ref and Testimonial in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"ref_and_testimonial.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"a9ca792fe30e4ab0982edbe4eaeb4340",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontWeight":"700",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":5,
                        "y":98},
                      "size":{
                        "width":150,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Expertise in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"expertise.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"8a47196aad3f420088144573216e183f",
                    "label":"",
                    "parentDynamicPanel":"d391f367d9984842b0b35554f6f00dc5",
                    "panelIndex":0,
                    "type":"textBox",
                    "styleType":"textBox",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Bold', 'Arial'",
                      "fontWeight":"700",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":5,
                        "y":23},
                      "size":{
                        "width":150,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "0eafc0e48886443d9e542f99ed5e42aa":{
      "scriptId":"u0",
      "304098334a3a436eba10bdfe9ddbdf3c":{
        "scriptId":"u1"},
      "d2ab26177fe94ea7a08e14bd1d7dbf1f":{
        "scriptId":"u2"},
      "7468122d704c4b28841f9104d62ed0c6":{
        "scriptId":"u3"},
      "b4699e436f284745b8eff14d44c41e0e":{
        "scriptId":"u4"},
      "ed3d4ae09a9a4c2faf68d7e710667f75":{
        "scriptId":"u5"},
      "454e729c1c3e46a5a1796054fef6b520":{
        "scriptId":"u6"},
      "2786e32a569f4cd7b2f615ada35b8147":{
        "scriptId":"u7"},
      "8765d64bf38a4b499bf0317d174aa62b":{
        "scriptId":"u8"},
      "088294d0af4044b8b630daffefe0bae3":{
        "scriptId":"u9"},
      "5f2c1186e4c3401cb42b8c9254353732":{
        "scriptId":"u10"},
      "d9f44c8297c541d7a6830cf4c4465c47":{
        "scriptId":"u11"},
      "8b189d5e9a09439a8c02f8ba2c984e9a":{
        "scriptId":"u12"},
      "1928623f2e2d4e3f9db1e9942b1e9697":{
        "scriptId":"u13"},
      "1aefd94ec79e4958b91b9a653c2cfdce":{
        "scriptId":"u14"},
      "e07464a117394704ae661dbe7ae08027":{
        "scriptId":"u15"},
      "3cbca462278a452a8605001a37f4a2f2":{
        "scriptId":"u16"},
      "1fc549ae4cee485eaf32e9aa544d9b2c":{
        "scriptId":"u17"},
      "0a7ce32f7f10455697cf4d25000e80d5":{
        "scriptId":"u18"},
      "06e98ae149ea42d293332f8d2d7f03bc":{
        "scriptId":"u19"},
      "93b616f0476843e280ecc97237d38803":{
        "scriptId":"u20"},
      "69d2ad3de5324d6ea231a8c6da194c42":{
        "scriptId":"u21"},
      "0f01366f0c984a7693f422b3718ba8bb":{
        "scriptId":"u22"},
      "71e65a8653c540008a8411748dc29f28":{
        "scriptId":"u23"},
      "ed498836e0be4dffaa8865b111ef5fac":{
        "scriptId":"u24"},
      "fced2d6de5b348ac92b496b2409acf9d":{
        "scriptId":"u25"},
      "5035dda8863442b48f723d72b55bc897":{
        "scriptId":"u26"},
      "f9c9b5abb089402aae3c6245a47bbb73":{
        "scriptId":"u27"},
      "07ad2066a5a140e09d2a5789515c9cd2":{
        "scriptId":"u28"},
      "100a622006304863b66ea184ac4326c1":{
        "scriptId":"u29"},
      "10335ed04b6641bab6dd417f730971ea":{
        "scriptId":"u30"},
      "152775203b2f486991bda12548664a94":{
        "scriptId":"u31"},
      "69dd513202904c33a2dab3ff2f4cf05d":{
        "scriptId":"u32"},
      "690906ffcc0342d0b5b433c1f959fc5d":{
        "scriptId":"u33"},
      "3574f624fcd24af484fecb5f5f64994e":{
        "scriptId":"u34"},
      "ba6bdb6b81a24125b6e1eb05b7beffb3":{
        "scriptId":"u35"}},
    "278515e4f5144b858ed66df9685b9651":{
      "scriptId":"u36"},
    "3054193e20524a489bfe464824653dba":{
      "scriptId":"u37"},
    "1c4355b83d5e42d2a5c298109617117e":{
      "scriptId":"u38"},
    "e0229760a30b4827a1292be5da3c055f":{
      "scriptId":"u39"},
    "91b090229e9b48dc985e3af9a7ca5838":{
      "scriptId":"u40",
      "04d8d786be5948b2a1280425060b7c44":{
        "scriptId":"u41"},
      "f42407941a7c4be9a80e1c1241fc1470":{
        "scriptId":"u42"},
      "a6b2e4aa0f0b4355a4b7742449541154":{
        "scriptId":"u43"},
      "ed64001a4f7b4eafbf19fd06486971f4":{
        "scriptId":"u44"},
      "9d2df81f1f4b4e0790c44855f0f444f9":{
        "scriptId":"u45"},
      "4609c8701294459b868e5eda24675efd":{
        "scriptId":"u46"},
      "d391f367d9984842b0b35554f6f00dc5":{
        "scriptId":"u47"},
      "4928784be90b43ec9fc731f44933e869":{
        "scriptId":"u48"},
      "ca8b8bf7135d479ebe208ebc3b3c7011":{
        "scriptId":"u49"},
      "cbbd110ef5e0402cad1d6672289a6e05":{
        "scriptId":"u50"},
      "8701e14eaa6946c280e59fd424ea4bdd":{
        "scriptId":"u51"},
      "a9ca792fe30e4ab0982edbe4eaeb4340":{
        "scriptId":"u52"},
      "8a47196aad3f420088144573216e183f":{
        "scriptId":"u53"}}}});